version: "3.3"
services:
  web:
    #build: .
    image: lksystem-web-app:latest
    #volumes:
    #  - ./:/app
    ports:
      - "3000:3000"
    links:
      - db:db
    env_file:
      - lk_credentials.env

  db:
    image: lksystem-sql:latest
    command: --init-file /data/application/init.sql
    restart: always
    container_name: test-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret2
      - MYSQL_DATABASE=helge99
      - MYSQL_USERNAME=root
    volumes:
      - my-datavolume:/var/lib/mysql
      # - ./init.sql:/data/application/init.sql
volumes:
  my-datavolume:
